source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WYMaterialButton_Example', :exclusive => true do
  pod "WYMaterialButton", :path => "../"
end

target 'WYMaterialButton_Tests', :exclusive => true do
  pod "WYMaterialButton", :path => "../"

  
end
