source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WYMaterialButton_Example' do 
  pod "WYMaterialButton", :path => "../"
end

post_install do |installer|
    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end
