//
//  WYMaterialButton.swift
//  WYMaterialButton
//
//  Created by Wang Yu on 9/24/15.
//
//

import UIKit
import QuartzCore

@IBDesignable
public class WYMaterialButton: UIButton {

    private let animationDuration = 0.6
    
    @IBInspectable
    public var touchLocationEnable: Bool = true
    
    @IBInspectable
    public var materialEffectPercent: CGFloat = 0.8 * 1.25 {
        didSet {
            self.materialEffectPercent = self.materialEffectPercent * 1.25
            self.configureMaterialView()
        }
    }
    
    @IBInspectable
    public var materialPressedColor: UIColor = UIColor.lightGrayColor() {
        didSet {
            self.materialView.backgroundColor = self.materialPressedColor
        }
    }
    
    @IBInspectable
    public var materialBackgroundColor: UIColor = UIColor.clearColor() {
        didSet {
            self.materialBackgroundView.backgroundColor = self.materialBackgroundColor
            self.materialPressedColor = autoGenerateDeeperColor(self.materialBackgroundColor)
            if autoBackgroundColor == true {
                self.backgroundColor = self.materialBackgroundColor
            }
        }
    }
    @IBInspectable
    var autoBackgroundColor: Bool = true
    
    private func autoGenerateDeeperColor(color: UIColor) -> UIColor {
        let colorComponent = CGColorGetComponents(color.CGColor)
        let newRed = max(colorComponent[0] - 0.05, 0)
        let newGreen = max(colorComponent[1] - 0.1, 0)
        let newBlue = max(colorComponent[2] - 0.13, 0)
        return UIColor(red: newRed, green: newGreen, blue: newBlue, alpha: 1)
    }
    
    public required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        configure()
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        configure()
    }
    
    let materialView = UIView()
    let materialBackgroundView = UIView()
    
    private func configure() {
        self.configureMaterialView()
        self.configureMaterialBackgroundView()
        
        self.layer.shadowRadius = 0
        self.layer.shadowOffset = CGSize(width: 0, height: 1)
        self.layer.shadowColor = UIColor(red: 255, green: 255, blue: 255, alpha: 0.5).CGColor
    }
    
    public override func layoutSubviews() {
        super.layoutSubviews()
        
        let previousCenter = self.materialView.center
        self.configureMaterialView()
        
        self.materialView.center = previousCenter
        self.materialBackgroundView.layer.frame = self.bounds
        
        let buttonMask = CAShapeLayer()
        buttonMask.path = UIBezierPath(roundedRect: self.bounds, cornerRadius: self.layer.cornerRadius).CGPath
        self.materialBackgroundView.layer.mask = buttonMask
    }
    
    
    private func configureMaterialView() {
        let materialEffectBounds: CGFloat = self.bounds.width * materialEffectPercent
        self.materialView.frame = CGRectMake(CGRectGetMidX(self.bounds) - materialEffectBounds/2, CGRectGetMidY(self.bounds) - materialEffectBounds/2, materialEffectBounds, materialEffectBounds)
        self.materialView.backgroundColor = self.materialPressedColor
        self.materialView.layer.cornerRadius = materialEffectBounds/2
    }
    
    private func configureMaterialBackgroundView() {
        self.materialBackgroundView.backgroundColor = self.materialBackgroundColor
        self.materialBackgroundView.frame = self.bounds
        self.layer.addSublayer(materialBackgroundView.layer)
        self.materialBackgroundView.layer.addSublayer(self.materialView.layer)
        self.materialBackgroundView.alpha = 0
    }
    
    public override func beginTrackingWithTouch(touch: UITouch, withEvent event: UIEvent?) -> Bool {
        self.materialBackgroundView.alpha = 1
        if self.touchLocationEnable == true {
            self.materialView.center = touch.locationInView(self)
        }
        self.materialView.transform = CGAffineTransformMakeScale(0.5, 0.5)
        
        UIView.animateWithDuration(animationDuration, delay: 0, options: UIViewAnimationOptions.CurveEaseOut, animations: { () -> Void in
                self.materialView.transform = CGAffineTransformIdentity
            }, completion: nil)
        
        return super.beginTrackingWithTouch(touch, withEvent: event)
    }
    
    public override func cancelTrackingWithEvent(event: UIEvent?) {
        super.cancelTrackingWithEvent(event)
        self.animationStopped()
    }
    
    public override func endTrackingWithTouch(touch: UITouch?, withEvent event: UIEvent?) {
        super.cancelTrackingWithEvent(event)
        self.animationStopped()
    }
    
    private func animationStopped() {
        self.materialBackgroundView.alpha = 1
        UIView.animateWithDuration(animationDuration, animations: { () -> Void in
            self.materialBackgroundView.alpha = 0
        })
    }
    
}
